version: "2"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    ports:
      - "5000:5000"
    command: bash -c "npm install && npm start"
