version: "2"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    ports:
      - "5000:5000"
    command: bash -c "yarn install && yarn start"
  
  test-watch:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
    command: yarn test-watch
